across-protocol/frontend-v1

src/components/PoolForm/PoolForm.tsx
https://app.shortcut.com/uma-project/story/2990/deposited-1-eth-in-the-pool-closed-the-confirmation-screen-and-it-showed-that-i-had-1-eth-as-fees-and-0-eth-as-my-deposit
=> default to 0 if fees are negative.

README.md, src/components/PoolForm/PoolForm.tsx, src/utils/constants.ts
Gas estimate was sometimes wrong. This sets an interval to update gas price, as well as increasing price buffer to prevent gas estimate errors. This also puts these vars as envs so we can update without pr if need be.
=> fix: increase gas estimate buffer

src/components/PoolForm/PoolForm.tsx, src/components/PoolForm/RemoveLiquidityForm.styles.ts, src/components/PoolForm/RemoveLiquidityForm.tsx, src/components/Tabs/Tabs.tsx, src/onboard-override.css, src/views/Pool.tsx
Following has been fixed:
1) Tabs widget has ability to set and change current default tab when it mounts:
https://app.shortcut.com/uma-project/story/2973/switching-currencies-in-pool-tab-should-not-reset-you-back-to-add-if-you-were-on-remove
2) Scroll to top when the deposit screen mounts:
https://app.shortcut.com/uma-project/story/2963/when-adding-removing-liquidity-and-getting-the-success-screen-my-screen-doesn-t-show-the-top-menu
3) Notify.js transaction modal has been updated
https://app.shortcut.com/uma-project/story/2965/transaction-modal-window-design
4) Updated fees percent span
https://app.shortcut.com/uma-project/story/3011/update-font-color-and-spacing-of-numbers-in-parenthesis-below
=> Batch fixes two nov 7th

src/Routes.tsx
https://app.shortcut.com/uma-project/story/3033/banner-should-appear-below-the-header-tabs-for-notifications-on-send-and-pool-tab
=> feat: swap banners appears under wallet

src/state/hooks.ts
This is a bit messy, but just repeating the logic is probably the simplest way to do this quick fix. In the future, we should probably link any error with an auto-disable of the send button.
=> fix: disable send button when the balance is insufficient

src/components/CoinSelection/CoinSelection.tsx
https://app.shortcut.com/uma-project/story/2954/when-entering-a-negative-value-on-the-send-page-the-error-message-appears-when-you-type-negative-and-then-goes-away-when
Shows an error if u input less than 0
=> fix: throw parsing error if send amount is negative

src/components/SendAction/SendAction.tsx, src/state/hooks.ts, src/views/Confirmation/Confirmation.styles.ts, src/views/Confirmation/Confirmation.tsx
https://app.shortcut.com/uma-project/story/2985/update-confirmation-page-showcasing-deposit-is-successful-and-funds-will-arrive-in-2-minutes
=> fix: add estimated wait to mainnet text on success page

src/components/Footer/Footer.tsx, src/views/About.tsx
following css fixes:
https://app.shortcut.com/uma-project/story/2926/banner-title-on-about-page-does-not-match-figma
https://app.shortcut.com/uma-project/story/2937/reduce-space-between-bottom-of-text-and-footers-reference-designs
https://app.shortcut.com/uma-project/story/3040/about-page-distance-between-bullets-and-text
=> About page css fixes nov 7th

src/components/AddressSelection/AddressSelection.tsx
https://app.shortcut.com/uma-project/story/2975/if-i-click-change-x-to-remove-the-current-address-cancel-and-then-open-up-the-change-dialog-again-the-address-box-will-still
resets the input box when user cancels change address
=> fix: reset change address box if cancelled

src/components/CoinSelection/CoinSelection.tsx, src/views/About.tsx
Previously parsing errors would not show up on send page when typing invalid values while your wallet was not connected. This changes how errors get cleared to maintain parsing errors if not connected. Previously all errors got cleared if not connected.
=> fix: allow parsing errors to show when not connected

src/components/CoinSelection/CoinSelection.tsx
To see bug: connect on the send tab with a wallet with 0 arb eth. then type characters in input box. it will say not enough balance. This only happens when you have 0 balance eth, and eth selected in dropdown. all other currencies dont have this problem. 
This just checks that the amount you have typed in is more than 0, before checking it against your balance. this seems to fix it.
=> fix: 0 balance account showing not enough funds for non numeric input

src/utils/constants.ts
Rate model was missing for UMA, making it impossible to do transfers.
Rate model was pulled from the UMIP here: https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-136.md.
Fixes #40.
=> fix: add rate model for UMA

src/components/PoolForm/PoolForm.tsx
fix inverted comparator to prevent showing negative fees
=> fix: fix fees earned to show correct value

src/utils/constants.ts, src/views/Confirmation/Confirmation.tsx
**Motivation**
This PR fixes a small bug with etherscan links on the confirmation screen. Also some `blockExplorerUrls` had a final `/` and some didn't, so I normalized them all to not have a final /
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to test.
=> fix(across): fix etherscan link

src/assets/border.svg, src/components/InformationDialog/InformationDialog.tsx, src/components/InformationDialog/index.ts, src/components/Layout/Layout.tsx, src/components/Section/Section.tsx, src/components/SendAction/SendAction.styles.ts, src/components/SendAction/SendAction.tsx
**Motivation**
This PR adds the information modal and is bundled with 2 additional small UI improvements, it makes the footers on the Send and Pool tab sticky again and it add the "ticket" border to the accent section like in the designs
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to test.
=> feat(across): add info modal and minor fixes

src/components/CoinSelection/CoinSelection.tsx, src/components/SendAction/SendAction.tsx, src/state/hooks.ts
Fix: Swapping Networks when USDC / WETH / UMA are selected won't crash application.
https://app.shortcut.com/uma-project/story/3251/selecting-different-tokens-can-crash-when-swapping-networks-in-send-tab
=> Bug/sc 3251/selecting different tokens can crash when

src/components/AddressSelection/AddressSelection.styles.ts, src/components/AddressSelection/AddressSelection.tsx, src/components/ChainSelection/ChainSelection.styles.tsx, src/components/ChainSelection/ChainSelection.tsx, src/components/CoinSelection/CoinSelection.styles.ts
Following fixes to dropdown:
L1 not L2 for ETH.
https://app.shortcut.com/uma-project/story/3358/ethereum-should-be-l1-not-l2-in-dropdown
ETH filtered out of from.
https://app.shortcut.com/uma-project/story/3375/remove-eth-from-the-from-dropdown-since-this-functionality-will-not-be-ready-until-post-launch-of-optimism-and-boba
Hover effect removed from "L1 to L2..."
https://app.shortcut.com/uma-project/story/3360/remove-hover-effect-on-transfers-between-l2-area-in-second-dropdown
Box shadow added.
box-shadow: inset 0 8px 8% rgba(45, 46, 51, 0.2);
https://app.shortcut.com/uma-project/story/3363/add-drop-shadow-on-dropdowns
=> Qa updates dropdown

src/components/Layout/Layout.tsx
This PR center aligns the "Powered By UMA" link as requested in https://app.shortcut.com/uma-project/story/3335/align-powered-by-uma-and-the-rest-of-the-footers 
Before:
After:
=> fix(across): center-align poweredByUMA

src/components/Tabs/Tabs.styled.tsx
This PR fixes https://app.shortcut.com/uma-project/story/2946/match-font-to-figma
=> fix(across): align font for pool tabs

src/components/ChainSelection/ChainSelection.styles.tsx, src/components/Header/Header.tsx, src/components/Layout/Layout.tsx, src/components/PoolSelection/PoolSelection.styles.ts, src/views/About.tsx
This PR fixes
- https://app.shortcut.com/uma-project/story/3164/update-the-name-of-the-send-tab-to-bridge
- https://app.shortcut.com/uma-project/story/2970/standardize-35px-spacing-on-both-tabs
- https://app.shortcut.com/uma-project/story/3329/update-doc-site-link-in-footer-to-docs-across-to
=> fix(across): minor css fixes

src/components/CoinSelection/CoinSelection.tsx, src/components/SendAction/SendAction.tsx, src/state/chainApi.ts, src/state/hooks.ts, src/utils/bridge.ts, src/utils/constants.ts
This uses the sdk to help calculate fees based on the "from chain" current timestamp. Anywhere the fees are queried, blocks are taken from the selected "from" chain rather than the "to" chain (mainnet).  This timestamp is passed into the lp fee calculator.
=> fix: use from chain block.timestamp for lp fee lookups

src/state/hooks.ts
This was caused by `fromChain` not being synced with the UI. If you switch the ui `from` to arbitrum and back, this fixes the issue without code changes, but this fix does the token lookup based on `currentlySelectedFromChain` which is always synced to the ui afaik
=> fix: fix token lookup from current from selection

package.json, src/utils/constants.ts, yarn.lock
https://app.shortcut.com/uma-project/story/3536/unable-to-send-uma-tokens-from-optimism-to-ethereum
Seems to be working after the change to the sdk
=> fix: bump sdk to fix sending uma from optimism

src/components/PoolForm/AddLiquidityForm.tsx, src/components/SendAction/SendAction.tsx
Blockchain shows error when they error out.
Note: Remove Liquidity already has an error handler.
=> feat: show global errors when blockchain calls error out.

src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/DepositSuccess.tsx, src/components/PoolForm/PoolForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx, src/views/Pool.tsx
This PR fixes https://app.shortcut.com/uma-project/story/3461/when-removing-liquidity-change-deposit-succeeded-to-withdrawal-succeeded
The solution I used is a bit hacky, but was the quickest one without having to colocate the add and remove liquidity forms
=> fix(across): change show success type and message

src/components/PoolForm/PoolForm.tsx
This PR fixes : https://app.shortcut.com/uma-project/story/3696/total-should-show-the-total-earned-by-the-user-not-the-total-pool-size
=> fix(across): change total to show individual position

src/components/CoinSelection/CoinSelection.tsx, src/components/SendAction/SendAction.tsx, src/state/hooks.ts, src/utils/bridge.ts, yarn.lock
Add support for L1 -> Boba transfers
Found a bug that was preventing the `Send` button to appear after a successful `Approve` action. It happened because, after approving, the app was checking the allowance for the deposit box, not for Optimism/Arbitrum/Boba Bridge contract
=> feat(across): ability to send funds from ethereum to boba

src/components/SendAction/SendAction.tsx
Bug: the bridging estimation time was not updating when switching back to L2 -> L1
=> fix: update estimation time on chain switch

src/views/Confirmation/Confirmation.tsx
This PR changes the receiving token on the confirmation screen to be ETH when a user sends WETH (as they will always receive ETH)
=> fix(across): use eth in deposit screen

src/components/AddressSelection/AddressSelection.tsx
This PR hides the "Change account" button when going from L1 to L2, as canonical bridges do not support it
=> fix(across): hide change account on L1 to L2 transfers

src/components/Header/MenuToggle.tsx
Removes outline for toggle button on mobile (may the accessibility gods have mercy)
=> fix(across): remove outline for toggle button

src/components/SendAction/SendAction.tsx
Changes symbol of token in "You will receive" section of the fees to ETH if sending WETH
=> fix(across): show eth received when sending weth

public/index.html, src/components/Dialog/Dialog.styles.tsx, src/components/GlobalStyles/GlobalStyles.tsx
This PR disables the zooming on iOS devices on inputs by setting inputs font-size to 16px
=> fix(across): disable zoom on input on iOS

src/components/Layout/Layout.tsx
=> across(fix): make powered by uma not overlap

src/components/PoolForm/PoolForm.tsx
Removes the "-" in front of the position, it sometimes showed -0 on iOS
=> fix(across): fix negative 0 on iOS

src/components/Header/Header.styles.tsx
This PR removes the outline from the mobile menu
=> fix(across): remove outline for mobile menu

src/components/Dialog/Dialog.styles.tsx
Before:
https://media.app.shortcut.com/api/attachments/files/clubhouse-assets/6050e9f3-ea3b-48d1-a78e-efcdcae6ce04/61f06c7f-7873-45e9-a667-7050aab717cd/IMG_2836.PNG
After:
=> across(fix): move modals upwards on mobile

src/components/ChainSelection/ChainSelection.styles.tsx, src/components/PoolSelection/PoolSelection.styles.ts, src/components/Section/Section.tsx
=> across(fix): reduce space over from on mobile

src/components/AddressSelection/AddressSelection.tsx, src/components/ChainSelection/ChainSelection.tsx, src/components/Wallet/Wallet.tsx, src/hooks/usePrevious.ts
Agreed work around: we still keep a default value, but we try to shift the dropdowns in Send to what the user has specified in their connected wallet the first time they connect, and the app will ask them to switch networks after.
=> feat: default users to the chain they have selected on clicking connect wallet

src/state/hooks.ts
This hides fee calculations until they are fetched for the currently selected currency. It also prevents sending before the updated calcs are loaded.
=> fix: only show fee calcs when done loading

src/components/PoolForm/PoolForm.tsx
format units return a formatted number string, like "1,000". This fails to parse as a number because of the comma.
before: 
after:
=> fix: number parsing causing NaN fees

src/components/CoinSelection/CoinSelection.styles.ts, src/components/PoolForm/AddLiquidityForm.tsx, src/hooks/useERC20.ts
The pool tab had some assumptions with approvals, these were made for expedience, but it was assumed we always allowed infinite, and we always assumed user was clicking to deposit max liquidity. 
This change makes it so we check allowance againts the amount to be added in the input  box.  Allowance queries have been separated from the check to prevent spamming the network while user is entering numbers.
=> fix: pool add liquidity approval checks amount to be added

src/components/PoolForm/AddLiquidityForm.tsx
previous update caused eth to require approvals, when it shouldnt need them. this prevents eth from showing approval button.
=> fix: disable approvals for eth pool

src/state/hooks.ts, src/utils/address.ts
Note: this attempts to fix some issues with sends to nonexistent contracts.
In v2, we might want to build a custom signer, but that seemed pretty tricky to get right without breaking any existing code. For expedience, this adds additional checks before all send transactions.
It also adds the chainId to the additional options in the L2 -> L1 case. It can't add this parameter to others since those transactions are produced inside of clients.
=> feat: add protection against sending to dead addresses

src/components/Header/Header.tsx, src/components/InformationDialog/InformationDialog.tsx, src/components/SendAction/SendAction.styles.ts, src/components/SendAction/SendAction.tsx, src/state/hooks.ts, src/utils/address.ts
Most of these changes are due to linting.  The functional change here was to keep the query params in the url when switching tabs. This is accomplished by adding location.search to the links in the tabs.
=> fix: allow query params to persist across tabs

src/components/Dialog/Dialog.styles.tsx
Remove min-height on the element. 
@chrismaree @Tommy1231232  let me know if this is acceptable on all screens.
=> fix: remove min height.

src/components/PoolSelection/PoolSelection.tsx
Note: removed position > 0 because I think it's intended to show to all users, but we can add it back in if need be.
=> linked changed; adjusted conditional

src/components/PoolSelection/PoolSelection.tsx
Signed-off-by: amateima <amatei@umaproject.org>
instructions url has been changed to https://docs.across.to/v2/migrating-from-v1
=> fix: replace migration instructions url
