across-protocol/frontend-v1

src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/PoolForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx, src/state/hooks.ts, src/views/Pool.tsx
Balance below AddLiquidity was incorrect after transaction. Refetch the balances after successful deposit / withdrawal
=> Refetch balance on deposit

src/Routes.tsx, src/components/CoinSelection/CoinSelection.styles.ts, src/components/Layout/Layout.tsx, src/components/PoolForm/AddLiquidityForm.styles.ts, src/components/PoolForm/DepositSuccess.tsx, src/components/PoolForm/PoolForm.styles.ts, src/components/PoolForm/PoolFormSlider.tsx, src/components/PoolForm/RemoveLiquidityForm.styles.ts, src/components/PoolForm/UserBalance.tsx, src/components/PoolSelection/PoolSelection.styles.ts, src/components/PoolSelection/PoolSelection.tsx, src/onboard-override.css, src/views/Confirmation/Confirmation.styles.ts, src/views/Confirmation/Confirmation.tsx, src/views/Pool.tsx
cleans up the pool tab CSS and fixes some styling bugs
=> fix(across): pool tab css cleanup

src/components/PoolForm/PoolForm.tsx
This error was causing input to fail
=> fix: catch all errors in input validation

src/components/CoinSelection/CoinSelection.styles.ts, src/components/PoolForm/AddLiquidityForm.styles.ts
=> fix: max button clickable area back to normal

src/components/PoolForm/RemoveLiquidityForm.styles.ts, src/components/PoolForm/RemoveLiquidityForm.tsx, src/onboard-override.css, src/utils/constants.ts, src/utils/format.ts
Following tickets:
1) Update to max percent buttons
https://app.shortcut.com/uma-project/story/2943/match-buttons-to-figma
2) Connect modal css
https://app.shortcut.com/uma-project/story/2912/connect-overlay-darken-background-and-button-tweaks
3) Added commas to formatted values
https://app.shortcut.com/uma-project/story/2921/add-comma-s-in-all-fields-where-it-can-be-greater-than-3-digits-on-pool-tab
4) UMA re-added.
https://app.shortcut.com/uma-project/story/3018/add-uma-token-to-dropdown-menues-on-the-send-and-pool-tab
=> Batch fixes nov 7th

src/components/PoolForm/DepositSuccess.tsx
=>  scroll to after deposit

src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx
=> wrong network switch works

src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx
=> balances update after 15 seconds

src/components/Wallet/Wallet.styles.ts, src/components/Wallet/Wallet.tsx
=> styles for unsupported network in wallet

src/components/SendAction/SendAction.tsx, src/utils/format.ts
This should fix the fee + received numbers not adding up.
LP fees were previously not being considered in the displayed fees.
=> fix: correct displayed fees

src/components/PoolForm/RemoveLiquidityForm.tsx, src/utils/index.ts, src/views/Pool.tsx
https://app.shortcut.com/uma-project/story/3020/fees-earned-appearing-negative
This just makes sure fees dont show less than 0
=> fix: fees less than 0 become 0

src/components/Footer/Footer.tsx, src/components/Header/Header.styles.tsx, src/components/Header/Header.tsx, src/views/About.tsx
=> feat(across): polish about

src/utils/constants.ts
=> feat(across): add uma to fe

public/index.html
=> fix(across): change meta description

src/components/Layout/Layout.tsx, src/views/About.tsx
=> fix(across): fix twitter link

public/index.html
=> meta tag for google search verification

src/components/SendAction/SendAction.tsx
**Motivation**
This PR breaks down the fees into bridge fees and ethereum gas fees
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to test.
=> feat(across): break down fees

package.json, yarn.lock
https://app.shortcut.com/uma-project/story/3161/bump-sdk-version-in-across-for-improved-apy-calcs
=> improve: bump sdk version for better apy calcs

package.json, yarn.lock
=> fix: bump sdk version for fixed pool size

package.json, public/sitemap.xml, src/sitemap-generator.js, src/sitemap-routes.js, yarn.lock
Sitemap generated using: https://www.npmjs.com/package/react-router-sitemap
=> sitemap generated.

public/index.html
=> share meta tags.

package.json, src/components/PoolForm/PoolForm.tsx, src/views/Pool.tsx, yarn.lock
Please take a look at the preview and let me know if this looks right.
=> feat: add utilization to pool tab

src/components/PoolForm/PoolForm.tsx
=> fix: update casing on text on pool tab

src/App.tsx
Motivation: Throw errors if environment variables are undefined as the app can unexpectedly crash without the Onboard key or Infura key.
=> bug: add check for environment variables.

src/components/CoinSelection/CoinSelection.tsx, src/components/SendAction/SendAction.tsx, src/state/hooks.ts, src/views/Confirmation/Confirmation.tsx
feat: UI points to correct block explorer and updated text.
Note: There is a HACK for optimism in this PR that should not be merged into master. Optimism timestamps are 10+ minutes behind mainnet.
=> Feature/sc 3092/updates to confirmation page and estimating

src/components/AddressSelection/AddressSelection.tsx, src/utils/constants.ts
Text updates to dropdowns.
https://app.shortcut.com/uma-project/story/3336/qa-on-dropdown-menus
=> text updates.

src/utils/constants.ts
Boba temp removed.
https://app.shortcut.com/uma-project/story/3430/remove-boba-from-dropdown-until-launch
=> boba commented out.

src/utils/constants.ts
=> Bug/sc 3389/when sending a deposit from optimism to ethereum

src/components/AddressSelection/AddressSelection.styles.ts, src/components/Buttons/BaseButton.tsx, src/components/CoinSelection/CoinSelection.styles.ts, src/components/PoolForm/AddLiquidityForm.styles.ts
This PR fixes https://app.shortcut.com/uma-project/story/2800/fix-hover-effect-on-max-button-and-change-button-per-designs
=> fix(across): align buttons to design

src/components/PoolForm/PoolForm.styles.ts, src/components/PoolForm/RemoveLiquidityForm.styles.ts, src/components/PoolForm/RemoveLiquidityForm.tsx
Error message.
Note: hard to test this as I'm not sure I can force the utilization rate to be low.
=> fix: error message shows up.

src/components/Dialog/Dialog.styles.tsx
This PR fixes https://app.shortcut.com/uma-project/story/3259/information-module-is-cutoff
=> fix(across): fix modal overflow

src/components/CoinSelection/CoinSelection.styles.ts
=> fix: removed box shadow.

package.json, src/components/PoolForm/PoolForm.tsx, src/views/Pool.tsx, yarn.lock
=> Feature/sc 3277/create the view for projected apy in the

src/Routes.tsx, src/context/ErrorContext.tsx, src/index.tsx, src/state/hooks.ts
1) Add banner to UI for global errors.
2) Infura issue throws if useBlock errors out.
=> feat: when infura goes down an error should appear

src/components/PoolForm/AddLiquidityForm.styles.ts, src/components/PoolForm/PoolForm.styles.ts, src/components/PoolForm/PoolForm.tsx, src/components/Tabs/Tabs.styled.tsx
This  PR fixes https://app.shortcut.com/uma-project/story/2901/spacing-on-pool-page-1
=> fix(across): make spacing consistent

src/utils/constants.ts
=> feat: boba added back in to dropdown.

src/Routes.tsx, src/components/SendAction/SendAction.tsx
Error shows up on top of page.
=> fix: no error reported when a contract isn t whitelisted

src/components/PoolForm/PoolForm.tsx, src/components/Tabs/Tab.tsx, src/components/Tabs/Tabs.styled.tsx
fixes https://app.shortcut.com/uma-project/story/2905/hover-effect-add-remove-tabs , https://app.shortcut.com/uma-project/story/3544/update-estimated-apy-to-current-apy
=> feat(across): add hover effect to tabs

src/components/Dialog/Dialog.styles.tsx, src/utils/constants.ts
CSS adjustment for not cutting off modal.
=> fix: adjusted info modal for zoomed screens

src/Routes.tsx, src/components/PoolForm/AddLiquidityForm.tsx, src/components/SendAction/SendAction.tsx, src/state/deposits.ts, src/state/send.ts, src/utils/constants.ts
Merge adds BOBA to list of potential L2->L1 options.
Merge when want to release to production.
=> release: Epic/boba

package.json, src/components/PoolForm/AddLiquidityForm.tsx, src/state/hooks.ts, src/utils/bridge.ts, src/utils/constants.ts, yarn.lock
Incorporates new gas estimation logic from sdk. Functionality should remain the same.
=> improve: update bridge utils to use latest relay gas calc in sdk

package.json, src/components/AddressSelection/AddressSelection.styles.ts, src/components/AddressSelection/AddressSelection.tsx, src/components/ChainSelection/ChainSelection.styles.tsx, src/components/ChainSelection/ChainSelection.tsx, src/components/CoinSelection/CoinSelection.styles.ts, src/components/CoinSelection/CoinSelection.tsx, src/components/PoolSelection/PoolSelection.styles.ts, src/components/PoolSelection/PoolSelection.tsx, yarn.lock
This PR adds transitions are requested in: https://app.shortcut.com/uma-project/story/2952/add-transitions-to-pool-and-about-page 
It is important to note to NOT update framer-motion as I'm using the last version that works with CRA and updating to latest would break it
=> feat(across): add dropdown transitions

src/components/PoolSelection/PoolSelection.styles.ts, src/components/Section/Section.tsx, src/state/hooks.ts, src/views/Confirmation/Confirmation.styles.ts, src/views/Pool.tsx
This PR accomplishes 3 things:
- It fixes https://app.shortcut.com/uma-project/story/2794/align-success-screen-ui-to-design
- It fixes https://app.shortcut.com/uma-project/story/2970/standardize-35px-spacing-on-both-tabs
- It fixes a memory leak in the useBalance hook and makes its API conform to all the other "on chain calls" hooks, returning a bigNumber instead of a string
=> fix(across): correct spacing on tabs and confirmation screen

src/components/AddressSelection/AddressSelection.tsx, src/components/SendAction/SendAction.tsx, src/state/hooks.ts, yarn.lock
Fees implemented in an upcoming PR ⏳
=> feat(across): ability to send funds from ethereum to arbitrum

src/components/InformationDialog/InformationDialog.tsx, src/components/SendAction/SendAction.tsx
Updated text.
Hide eth gas fee on mainnet swap.
=> fix: updated with notes from Tom

src/components/InformationDialog/InformationDialog.tsx, src/components/SendAction/SendAction.styles.ts, src/components/SendAction/SendAction.tsx
1) Copy update (unticketed)
2) Added info below Send button when on L1:
https://app.shortcut.com/uma-project/story/3754/add-l1-to-l2-transfers-use-the-destination-s-canonical-bridge-below-send-button-for-l1-to-l2-transfers-only
=> feat: copy update for L1 to L2

src/components/CoinSelection/CoinSelection.tsx, yarn.lock
1) Coin Selection Dropdown needs to be tracked -- some coins don't exist on certain chains, so the coin needs to be changed.
2) Null pointer fix for tokensList[selectedIndex]
Note: This may also fix --  https://app.shortcut.com/uma-project/story/3763/if-i-select-to-send-assets-from-ethereum-to-arbitrum-and-select-weth-and-an-amount-and-then-change-the-to-field-to-optimism
=> fix: CoinSelection dropdown needs to be controlled

src/components/SendAction/SendAction.tsx
=> fix: units added back in

src/components/CoinSelection/CoinSelection.tsx
https://app.shortcut.com/uma-project/story/3759/fix-across-crash
When changing the selected dropdown item, we also need to change the token
=> fix: change token when switching chains

package.json, src/components/AddressSelection/AddressSelection.tsx, src/components/ChainSelection/ChainSelection.tsx, src/components/CoinSelection/CoinSelection.tsx, src/components/InformationDialog/InformationDialog.tsx, src/components/SendAction/SendAction.styles.ts, src/components/SendAction/SendAction.tsx, src/state/chainApi.ts, src/state/hooks.ts, src/utils/bridge.ts, src/utils/constants.ts, src/views/Confirmation/Confirmation.tsx, yarn.lock
=> release: L1 to L2

src/components/Tabs/Tabs.styled.tsx
changes font of pool tabs to normal
=> fix(across): make tabs font normal

src/utils/constants.ts
Adds UMA to assets sendable from Boba
=> feat(across): add uma on boba

src/components/SendAction/SendAction.tsx
This PR changes "canonical" to "native" in the copy
=> fix(across): change canonical to native

src/components/PoolForm/RemoveLiquidityForm.tsx
=> fix(across): change fees claimed to fees earned

src/components/Header/Header.styles.tsx
This PR moves the breakpoint for the mobile headers down
=> fix(across): move brekpoint for headers

package.json, yarn.lock
=> improve: bump sdk to fix apy estimations

src/onboard-override.css
This PR aligns the MM onboard button 
=> fix(across): align mm button and text on mobile

src/components/PoolForm/PoolForm.styles.ts, src/views/Pool.tsx
=> fix(across): restore bg to prevent cutoff

src/utils/format.ts, src/views/Confirmation/Confirmation.styles.ts, src/views/Confirmation/Confirmation.tsx
=> fix(across): shorten address on smaller screens

src/components/Dialog/Dialog.styles.tsx
Before: See pics in the story
After: 
=> fix(across): remove outline for modal 

src/components/PoolForm/PoolForm.tsx, src/views/Pool.tsx
=> across(fix): change my deposit to position size

package.json, src/components/GlobalStyles/GlobalStyles.tsx, src/components/Wallet/Wallet.styles.ts, src/components/Wallet/Wallet.tsx, src/hooks/useClickOutsideModal.ts, src/utils/constants.ts, yarn.lock
Disconnect functionality in wallet.
https://app.shortcut.com/uma-project/story/2559/add-ability-to-disconnect-wallet
=> feat: ability to disconnect wallet.

src/components/PoolForm/PoolFormSlider.tsx, src/components/PoolForm/RemoveLiquidityForm.styles.ts, src/components/PoolForm/RemoveLiquidityForm.tsx
Before: See pic in the story
After
=> across(fix): remove padding from remove info

vercel.json
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
=> Add headers config

src/onboard-override.css, src/utils/constants.ts
Note: This only works on mobile.
Story details: https://app.shortcut.com/uma-project/story/3084
=> feat: Add coinbase wallet to Across

src/components/AddressSelection/AddressSelection.tsx, src/components/ChainSelection/ChainSelection.tsx, src/components/Wallet/Wallet.tsx, src/utils/constants.ts
fromChain and toChain need to be dispatched from new useEffect to sync FE state.
=> fix: dispatch other actions 

src/components/Dialog/Dialog.styles.tsx
=> fix: lower top percent to fix viewport

src/onboard-override.css
Story details: https://app.shortcut.com/uma-project/story/4345
=> fix: adjusted modal

src/utils/constants.ts
=> bug: remove coinbase wallet

src/components/ChainSelection/ChainSelection.styles.tsx, src/components/CoinSelection/CoinSelection.styles.ts
fixes https://app.shortcut.com/uma-project/story/4621/create-a-shadow-behind-the-from-chain-dropdown
=> fix(across): add dropdown shadow

src/components/CoinSelection/CoinSelection.styles.ts
This PR fixes: https://app.shortcut.com/uma-project/story/4457/green-box-appears-around-input-field-on-safari
=> fix(across): remove outline from input

src/utils/constants.ts
=> chore: remove wallet connect from onboard

src/components/InformationDialog/InformationDialog.tsx
Removed unnecessary " in the information module
=> updated grammar

src/components/Layout/Layout.tsx
=> fix: removed links

src/components/GlobalStyles/GlobalStyles.tsx, src/components/Header/Header.styles.tsx, src/views/Send.tsx, yarn.lock
Adjusted padding slightly. Can you lmk if this is ok @Tommy1231232 ?
=> fix: adjusted padding; fixed warning.

api/limits.js, api/suggested-fees.js, api/utils.js, src/utils/bridge.ts
This also includes a bug fix where the liquidReserves used to determine if a transfer is allowed could be incorrect.
=> feat: add /limits api endpoint so integrators can determine the range of deposits allowed

src/Routes.tsx, src/components/SendAction/SendAction.styles.ts, src/components/SendAction/SendAction.tsx, src/state/connection.ts, src/state/hooks.ts, src/utils/constants.ts, src/utils/onboard.ts
https://app.shortcut.com/uma-project/story/5104/re-add-walletconnect-to-across-and-if-users-are-connected-with-walletconnect-show-a-disclaimer
=> feat: add WalletConnect and show disclaimer

README.md, src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/PoolForm.styles.ts, src/components/PoolForm/PoolForm.tsx, src/utils/constants.ts
=> feat: block adding liquidity when REACT_APP_BLOCK_POOL_LIQUIDITY is true

README.md, src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolSelection/PoolSelection.styles.ts, src/components/PoolSelection/PoolSelection.tsx, src/utils/constants.ts, src/views/Pool.tsx
REACT_APP_MIGRATION_POOL_V2_WARNING must be set to "true" in  .env file.
=> feat: Block liquidity and show warning if user has a position on v1

README.md, src/components/ChainSelection/ChainSelection.styles.tsx, src/components/ChainSelection/ChainSelection.tsx, src/components/SendAction/SendAction.tsx, src/utils/constants.ts
Story details: https://app.shortcut.com/uma-project/story/5573
=> feat: [sc-5573] add env to disable send button in across v1 and add banner

src/Routes.tsx, src/components/PoolForm/PoolForm.tsx
Story details: https://app.shortcut.com/uma-project/story/5586
Includes: https://app.shortcut.com/uma-project/story/5587/link-to-v2-across-to-in-pool-warning-in-across-v1
=> fix: [sc-5586] change link to medium article in across v1

src/Routes.tsx
Story details: https://app.shortcut.com/uma-project/story/5788
=> chore: update banner text.
